insert ignore into `forum` (`name`, `spider`) values 
	('Alphabay', 'alphabay_forum'), 
	('Dream Market Forum', 'dreammarket_forum'),
	('Trade Route Forum', 'traderoute_forum'),
	('RsClub Market Forum', 'rsclub_forum'),
	('Darknet Heroes League', 'dhl_forum'),
	('Apple Market Forum', 'applemarket_forum'),
	('House Of Lions', 'houseoflions_forum'),
	('Aero Forum', 'aero_forum'),
	('Cannabis Growers & Merchants Coop Forum', 'cgmc_forum'),
    ('Wall Street Forum', 'wallstreet_forum'),
    ('Onionland', 'onionland_forum'),
    ('Olympus Market Forum', 'olympusmarket_forum'),
    ('Berlusconi Market Forum', 'berlusconimarket_forum'),
    ('Italian Deep Web Forum', 'italiandeepweb_forum'),
    ('Berlusconi Market Forum', 'berlusconimarket_forum'),
    ('French Dark Place Forum', 'frenchdarkplace_forum'),
    ('Mercado Negro Forum', 'mercadonegro_forum'),    
    ('Zion Market Forum', 'zionmarket_forum'),
    ('Apollon Market Forum', 'apollonmarket_forum'),
    ('French Deep Web Forum', 'frenchdeepweb_forum'),
    ('Italian Darknet Community 2.0', 'idc2_forum'),
    ('The Majestic Garden Forum', 'majesticgarden_forum'),
    ('Silk Road 3.1 Forum', 'silkroad_forum');

insert ignore into `user_propkey` (`name`, `prettyname`) values 
	('joined_on', 'Joined on'),
	('likes_received', 'Likes received'), 
	('last_activity', 'Last activity'), 
	('avatar', 'Avatar'), 
	('message_count', 'Message count'), 
	('user_id', 'User ID'), 
	('title', 'Title'), 
	('banner', 'Banner'),
	('location', 'Location'), 
	('website', 'Website'), 
	('signature', 'Signature'), 
	('post_count', 'Post Count'), 
	('last_post', 'Last post on'),
	('realname', 'Real name'),
	('jabber', 'Jabber'),
	('microsoft_account', 'Microsoft Account'),
	('icq', 'ICQ'), 
	('yahoo_messenger', 'Yahoo Messenger'),
	('membergroup', 'Member group'),
	('postgroup', 'Post group'),
	('reputation_power', 'Reputation power'),
	('rep_bars', 'Reputation Bars'),
	('reputation', 'Reputation'),
	('stars', 'Stars'),
	('karma', 'Karma'),
	('post_per_day', 'Post per days'),
	('age', 'Age'),
	('group', 'Group'),
	('last_active', 'Last active'),
	('gender', 'Gender'),
	('custom_title', 'Custom title'),
	('personal_text', 'Personal text'),
	('msn', 'MSN Messenger'),
	('followers', 'Followers'),
    ('pgp_key', 'PGP key'),
    ('average_rating', 'Average rating'),
    ('rating_count', 'Ratings'),
    ('email', 'Email'),
    ('trophy_points', 'Trophy points'),
    ('birthday', 'Birthday'),
    ('occupation', 'Occupation'),
    ('aol', 'AOL Messenger'),
    ('user_sales', 'Sales'),
    ('user_buys', 'Buys'),
    ('awards', 'Awards'),
    ('rank', 'Rank'),
    ('warning_level', 'Warning level');
